### PR TITLE
Whitespace related code tidying

### PR DESCRIPTION
**Pull request by harry-wood**
Assorted whitespace related code tidying. Trivial. No actual code changes

I wanted to fix line endings to help with a build problem, but thought I'd put it through a couple of trivial whitespace related rubocops at the same time.

### CODE REVIEW

**Comment by harry-wood** [comment]
You know rubocop? I'd be in favour of unleashing rubocop on this code with a few less trivial "cops" which would improve, or at least standardise the code style more...  but you might not like it. The fixes I've done here are entirely uncontroversial though.

**Comment by geraldb** [comment]
@harry-wood  first thanks again for running pluto on openstreet maps blogs.    

Note: I'm not really a "fan" of rubycop to put it mildy - sorry to disappoint.  However, I've merged your changes.  

As said before I'm more than happy to assist if you tell what functionality you're trying to add / change / improve?  Again really happy to see the first contributions. Keep it up.  The idea of all these modular gems is / was to make it easier to contribute.

Maybe you can open an issue were we can "centralize" the discussion / notes? Again happy to point you to the gem / code for easier getting started.  Or any other way.  Cheers.

**Comment by harry-wood** [comment]
I didn't used to like rubocop but I grew to like it more. Some "cops" are more annoying that others. Generally the more opinionated ones.

You can actually pick cops and run them individually. These very uncontroversial ones can even be auto-corrected like so:
`rubocop --only Layout/TrailingWhitespace,Layout/Tab,Layout/TrailingBlankLines --auto-correct`

**Comment by geraldb** [comment]
Thanks for helping me understand rubocop. I see your points.  Pick the rules / "cops" that you agree on etc.  Sorry I'm burned / traumatized at my "enterprise" day job where most enforced code-linter rules to "standardize" are enforced and mostly idiotic. Consensus is hard :-) Maybe a blockchain mining pool is the solution :-)

**Pull request merged**
